// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMeiyf6-jXaBzQX8LqhM8JapxOpFDnRek',
    appId: '1:168225768612:web:2e43d13c23f93ea11b5231',
    messagingSenderId: '168225768612',
    projectId: 'to-do-app-mimo',
    authDomain: 'to-do-app-mimo.firebaseapp.com',
    storageBucket: 'to-do-app-mimo.appspot.com',
    measurementId: 'G-JJBEX176P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLFoU7X0HNABflbKxEIocdiMlMhhhuqUc',
    appId: '1:168225768612:android:c9e293a7c6b6bcff1b5231',
    messagingSenderId: '168225768612',
    projectId: 'to-do-app-mimo',
    storageBucket: 'to-do-app-mimo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUs0THZx_B-eQJZol2iZ_XBhV_9UjFTP8',
    appId: '1:168225768612:ios:c910379b66c2331b1b5231',
    messagingSenderId: '168225768612',
    projectId: 'to-do-app-mimo',
    storageBucket: 'to-do-app-mimo.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUs0THZx_B-eQJZol2iZ_XBhV_9UjFTP8',
    appId: '1:168225768612:ios:c910379b66c2331b1b5231',
    messagingSenderId: '168225768612',
    projectId: 'to-do-app-mimo',
    storageBucket: 'to-do-app-mimo.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMeiyf6-jXaBzQX8LqhM8JapxOpFDnRek',
    appId: '1:168225768612:web:400bb9ad6604e2e01b5231',
    messagingSenderId: '168225768612',
    projectId: 'to-do-app-mimo',
    authDomain: 'to-do-app-mimo.firebaseapp.com',
    storageBucket: 'to-do-app-mimo.appspot.com',
    measurementId: 'G-5FZ5LGVCQ8',
  );
}
